// flow-typed signature: 7b5e00743ba2483bd656ff59c9bd019a
// flow-typed version: <<STUB>>/react-hot-keys_v1.2.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hot-keys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hot-keys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hot-keys/es/index' {
  declare module.exports: any;
}

declare module 'react-hot-keys/lib/index' {
  declare module.exports: any;
}

declare module 'react-hot-keys/umd/react-hot-keys' {
  declare module.exports: any;
}

declare module 'react-hot-keys/umd/react-hot-keys.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hot-keys/es/index.js' {
  declare module.exports: $Exports<'react-hot-keys/es/index'>;
}
declare module 'react-hot-keys/lib/index.js' {
  declare module.exports: $Exports<'react-hot-keys/lib/index'>;
}
declare module 'react-hot-keys/umd/react-hot-keys.js' {
  declare module.exports: $Exports<'react-hot-keys/umd/react-hot-keys'>;
}
declare module 'react-hot-keys/umd/react-hot-keys.min.js' {
  declare module.exports: $Exports<'react-hot-keys/umd/react-hot-keys.min'>;
}
