// flow-typed signature: 3ecb531f5e153cee3461ef4e1681ab2d
// flow-typed version: <<STUB>>/whatwg-fetch_v3.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'whatwg-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'whatwg-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'whatwg-fetch/dist/fetch.umd' {
  declare module.exports: any;
}

declare module 'whatwg-fetch/fetch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'whatwg-fetch/dist/fetch.umd.js' {
  declare module.exports: $Exports<'whatwg-fetch/dist/fetch.umd'>;
}
declare module 'whatwg-fetch/fetch.js' {
  declare module.exports: $Exports<'whatwg-fetch/fetch'>;
}
